

services:
  app:
    image: $IMAGE_NAME
    platform: linux/amd64
    build:
      context: .
    restart: on-failure
    env_file: .env
    ports:
      - 3000:$NODE_LOCAL_PORT
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - MONGODB_HOST=$MONGODB_HOST
      - PORT=$PORT
      - EMAIL_HOST=$EMAIL_HOST
      - EMAIL_PORT=$EMAIL_PORT
      - EMAIL_PASS=$EMAIL_PASS
      - EMAIL_SECURE=$EMAIL_SECURE
      - EMAIL_TO=$EMAIL_TO
      - EMAIL_USER=$EMAIL_USER
      - EMAIL_SERVICE=$EMAIL_SERVICE
      - ATLAS_URI=$ATLAS_URI
      - DB_HOST=$MONGODB_HOST
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_PORT
      - JWT_SECRET=$JWT_SECRET
    stdin_open: true
    tty: true
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - 27017:$MONGODB_PORT
    volumes:
      - mongo:/data/db

volumes:
  mongo: